### ISSUE TITLE
Running relna.py produces an error.

### ISSUE THREAD

**Issue by minseven** [Rostlab/relna#23]
Hi,

I am trying to run relna.py but I keep having the following error:

msgkim@taglabdell:~/relna$ python3 relna.py -c relna/data/ -s "Conclusion: we find that Ubc9 interacts with the androgen receptor (AR), a member of the steroid receptor family of ligand-activated transcription factors. In transiently transfected COS-1 cells, AR-dependent but not basal transcription is enhanced by the coexpression of Ubc9."
Due to a dependence on GNormPlus, running nala with -s and -d switches might take a long time.
/usr/local/lib/python3.5/dist-packages/nalaf-0.2.1-py3.5.egg/nalaf/structures/data.py:916: UserWarning: "annotations" (and "predicted_annotations") are meant to be "entities". This and related attributes will soon be renamed
  warnings.warn('"annotations" (and "predicted_annotations") are meant to be "entities". This and related attributes will soon be renamed')
Traceback (most recent call last):
  File "relna.py", line 61, in <module>
    pipeline = RelationExtractionPipeline(PRO_CLASS_ID, MUT_CLASS_ID, PRO_REL_MUT_CLASS_ID, feature_set=feature_set)
  File "/usr/local/lib/python3.5/dist-packages/nalaf-0.2.1-py3.5.egg/nalaf/structures/relation_pipelines.py", line 65, in __init__
    SentenceFeatureGenerator(f_counts_individual=1),
TypeError: __init__() missing 14 required positional arguments: 'f_counts_total', 'f_counts_in_between_individual', 'f_counts_in_between_total', 'f_order', 'f_bow', 'f_pos', 'f_tokens_count', 'f_tokens_count_before', 'f_tokens_count_after', 'f_sentence_is_negated', 'f_main_verbs', 'f_entity1_count', 'f_entity2_count', and 'f_diff_sents_together_count'

Do you know the cause of this error? Thanks.

**Comment by juanmirocks** [comment]
Thank you very much for your report!! @minseven 

I'm afraid I cannot maintain this software at the moment. However, I will be moving gradually this and more functionality to tagtog.net, which will be maintained. I will update here when a relna-like relation extractor is provided on tagtog.
